[package]
name = "versioned-structs"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = { version = "1.0.103", features = ["full", "extra-traits"]}
proc-macro2 = "1.0.47"
bae = "0.1.7"
